export const ARTICLE_TITLE_UPDATE = "articles/artcleTitleUpdate"
export const ARTICLE_DESCRIPTION_UPDATE = "articles/artcleDescriptionUpdate"
export const ARTICLE_TEXT_UPDATE = "articles/artcleTextUpdate"
export const ARTICLE_CATEGORY_UPDATE = "articles/articleCategoryUpdate"
export const ARTICLE_COMMENTS_UPDATE = "article/articleCommentsUpdate"
export const ARTICLE_ADD = "articles/articleAdd"
export const GET_ARTICLE = "articles/getArticle"
export const ARTICLE_FILTER = "article/articleFilter"
export const ARTICLE_FILTER_BY_SEARCH = "article/articleFilterBySearch"

